lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import (index, add_friend, validate_npm, delete_friend, 
                    friend_list, get_mahasiswa, friend_page, get_friend_list)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^get-friend-data/$', get_friend_list, name='get-friend-data'),
    url(r'^get-mahasiswa-list/$', get_mahasiswa, name='get-mahasiswa'),
    url(r'^(?P<npm>[0-9]+)/$', friend_page, name='friend-page')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    # doesnt have to import the urls hoho
    url(r'^lab-9/', include('lab_9.urls', namespace='lab-9')),
    url(r'^lab-10/', include('lab_10.urls', namespace='lab-10')),
    # ---------------------------------------------------------------------
    url(r'^$', RedirectView.as_view(permanent=True, url='/lab-4/'), name='index'),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)
	added_at = models.DateField(auto_now_add=True)

	def __str__(self):
		return "%s - %s" % (self.npm, self.friend_name)

lab_7/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.http import Http404

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json
import requests

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada
    mahasiswa_list = get_mahasiswa_page(1)
    friend_list = Friend.objects.all()

    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    html = 'lab_7/daftar_teman.html'
    response['friend_list'] = Friend.objects.all().order_by('npm')
    return render(request, html, response)

def get_friend_list(request):
    if(request.method == 'GET'):
        friend_list = []
        for i in Friend.objects.all().order_by('npm'):
            friend_list.append(model_to_dict(i))

        return JsonResponse({'status_code':200, 'friends':friend_list})
    raise Http404

def get_mahasiswa_page(page):
    return csui_helper.instance.get_mahasiswa_list(page)

def get_mahasiswa(request):
    if request.method == 'GET':
        page = request.GET.get('page')
        return JsonResponse({'status':200, 'page':page, 'mahasiswa':get_mahasiswa_page(page)})

@csrf_exempt
def add_friend(request):
        
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']

        if not check_friend(npm) and csui_helper.instance.validate_npm(npm):
            friend = Friend (friend_name=name, npm=npm)
            friend.save()
        
            return JsonResponse({
                'status': 200,
                'friend_name':friend.friend_name,
            })
    
    return JsonResponse(status=405, data={'error':'message'})

def delete_friend(request):
    if(request.method == 'GET'):
        if(request.GET.get('id')):
            data = get_object_or_404(Friend, id=request.GET.get('id'))
        elif(request.GET.get('npm')):
            data = get_object_or_404(Friend, npm=request.GET.get('npm'))
        
        data.delete()
        return JsonResponse({'status_code':200})

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': check_friend(npm)
    }
    return JsonResponse(data)

def check_friend(npm):
    return Friend.objects.filter(npm=npm).count() > 0 

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    st = struct[0]["fields"]
    st['id'] = struct[0]['pk']
    data = json.dumps(st)
    return data

def friend_page(request, npm):
    html = 'lab_7/friend_page.html'
    get_object_or_404(Friend, npm=npm)
    data = csui_helper.instance.get_mahasiswa_data(npm)
    
    try:
        API_REQ = 'https://maps.googleapis.com/maps/api/geocode/json?address={},+ID& \
                    key=AIzaSyADkxOuul50UxK2DZP6W2f0DmTM92RyS9k'.format(data['zipcode'])
        res = requests.request('GET', API_REQ).json()['results'][0]
    
        return render(request, html, {
                'friend':data,
                'longitude':res['geometry']['location']['lng'],
                'latitude':res['geometry']['location']['lat'],
            })
    except:
        raise Http404

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <h2> Teman Saya </h2>
            <div class="list-group" id="friend-list">
                <!-- data -->
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function() {
        $.ajax({
            method: 'GET',
            url: '{% url "lab-7:get-friend-data" %}',
            success: function(response){
                lst_friend = response.friends;
                
                for(var i=0; i < lst_friend.length; ++i){
                    friend = JSON.parse(lst_friend[i]);
                    html = '<div class="list-group-item" id="friend-'+friend.id+'"> \
                                <a class="list-group-item clearfix" style="width:100%" href="/lab-7/' + friend.npm +'/">' +
                                    friend.friend_name + " " + "(" + friend.npm + ")"
                                + '</a> \
                                <a class="list-group-item pull-left" onclick="deleteFunc('+friend.id+')">X</a> \
                            </div>';
                    $('#friend-list').append(html);
                }
            },
            error: function(response){
                html = '<div class="alert alert-danger text-center">\
                            <strong>Opps!</strong> Tidak ada teman\
                        </div>';
                $('#friend-list').append(html);
            }
        })
    })

    const deleteFunc = function(id) {
        $.ajax( {
            method:'GET',
            url: '{% url "lab-7:delete-friend" %}',
            data: {
                'id':id,
            },
            success: function(response){
                $('#friend-'+id).remove();
            },
            error: function(response){
                alert("ID tidak ditemukan")
            }
        })
    }
</script>
{% endblock %}

lab_7/templates/lab_7/friend_page.html
{% extends "lab_7/layout/base.html" %}
{% load static %}
{% block content %}
<section>
    {% if friend %}
    <div class="friend-page">
        <div class="data">
            <h2>{{friend.nama}}</h2>
            <h3>{{friend.program}}</h3>
            <span>{{friend.npm}}</span><br>
            <span>{{friend.kota_lahir}}, {{friend.tgl_lahir}}</span><br>
            <p>{{friend.alamat}}</p>
        </div>
    </div>
    <div class="map-page">    
        <div id="map" style="margin:0" ></div>
        <span id="friend-pos">{{latitude}} {{longitude}}</span>
        <span class="privacy">For the privacy protection, this is not the exact location</span>
    </div>
    {% endif %}
</section>
{% endblock %}
{% block javascript %}
<script>
      function initMap() {
        //   https://developers.google.com/maps/documentation/javascript/adding-a-google-map
        var loc = {lat: {{latitude}}, lng: {{longitude}}};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: loc
        });
        var marker = new google.maps.Marker({
          position: loc,
          map: map
        });
      }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyADkxOuul50UxK2DZP6W2f0DmTM92RyS9k&callback=initMap">
</script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group" id="mhs-list">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                <div style="width:100%">{{ mahasiswa.nama }} ({{ mahasiswa.npm }})</div>
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div id="loading">
                Loading...
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    $(document).ready (function(){
        $('#loading').hide();
    })
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url 'lab-7:add-friend' %}",
            data: {name: nama, npm: npm},
            success : function (friend) {
                if(friend.status == 200){
                    html = '<a class="list-group-item clearfix">' +
                        friend.friend_name +
                        '</a>';
                    $("#friend-list").append(html)
                } else {
                    alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
                }
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };
    $("#add-friend").on("submit", function () {
        name = $("#field_name").val()
        npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });
    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}' ,
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
    const win = $(window);
    var page = 2;
    var progress = true;
    win.scroll(function(){
        if(win.scrollTop() + win.height() > $(document).height()-10 && progress){
            progress = false;
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-mahasiswa" %}',
                data: {
                    'page':page,
                },
                dataType: 'json',
                beforeSend: function () {
                    $("#loading").show();
                },
                success: function (data) {
                    // bug: double request
                    // data.page == page is to prevent same data added twice because double request 
                    if(data.status == 200 && data.page == page){
                        
                        lst_mhs = data.mahasiswa;
                        for(var i=0; i < lst_mhs.length; ++i){
                            mhs = lst_mhs[i];
                            
                            html = '<a class="list-group-item clearfix">'+ mhs.nama +
                                    ' ('+ mhs.npm +')';
                            html += '<span class="pull-right">\
                        <span class="btn btn-xs btn-default" onClick="addFriend($(mhs.nama),$(mhs.npm))">\
                            Tambah sebagai teman\
                        </span>\
                    </span></a>'
                            
                            $('#mhs-list').append(html);
                        }

                        page++;
                    }
                },
                complete: function () {
                    progress = true;
                    $('#loading').hide();
                }
            })
        }
    })
</script>
{% endblock %}