lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import (index, add_friend, validate_npm, delete_friend, 
                    friend_list, get_mahasiswa, friend_page, get_friend_list)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^get-friend-data/$', get_friend_list, name='get-friend-data'),
    url(r'^get-mahasiswa-list/$', get_mahasiswa, name='get-mahasiswa'),
    url(r'^(?P<npm>[0-9]+)/$', friend_page, name='friend-page')
]

lab_8/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    # doesnt have to import the urls hoho
    url(r'^lab-9/', include('lab_9.urls', namespace='lab-9')),
    url(r'^lab-10/', include('lab_10.urls', namespace='lab-10')),
    # ---------------------------------------------------------------------
    url(r'^$', RedirectView.as_view(permanent=True, url='/lab-4/'), name='index'),
]

lab_8/models.py
from django.db import models

# Create your models here.

lab_8/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    html = 'lab_8/lab_8.html'
    return render(request, html, {})

lab_8/templates/lab_8/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>&copy; Made with Love by {{author}}</p>

lab_8/templates/lab_8/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='{% url "lab-7:index" %}'>Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- link -->
          <li><a href='{% url "lab-7:get-friend-list" %}'>Post</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>